// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCu-c4E-25mf88GWssQcPLj_uciOu2QpIg',
    appId: '1:294318007510:android:7ca085493f7f7b81459577',
    messagingSenderId: '294318007510',
    projectId: 'wounddetection-aa1ee',
    storageBucket: 'wounddetection-aa1ee.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBzrOnqb6tgy9wYttYz-cWnidBftmua_dU',
    appId: '1:294318007510:ios:e23258d92bb59f24459577',
    messagingSenderId: '294318007510',
    projectId: 'wounddetection-aa1ee',
    storageBucket: 'wounddetection-aa1ee.appspot.com',
    androidClientId: '294318007510-g3nio6ho4ncv7dj8m9h71vb1h66pt93a.apps.googleusercontent.com',
    iosClientId: '294318007510-mmb06aea7uq8fco5jq1bppuhtg5ark8o.apps.googleusercontent.com',
    iosBundleId: 'com.numluni.wounddetectionsystem',
  );
}
