name: Flutter CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # Set up Flutter environment
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.3.2' # specify the Flutter version you need

      - name: Install dependencies
        run: flutter pub get

      # Optional: Verify formatting
      - name: Verify formatting
        run: flutter format --set-exit-if-changed

      - name: Analyze project source
        run: flutter analyze

      - name: Run tests
        run: flutter test
